[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"

[features]
dhat-heap = []

[dependencies]
dhat.workspace = true
anyhow.workspace = true
rstest.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "benchmark"
harness = false
